version: "2"
services:
  app:
    build: ./app
    links:
      - database
    ports:
      - "5000:5000"
  database:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro